//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

using System.Xml.Serialization;

namespace Onyx.XPatch.Console.xml {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class ConfigXML {
        
        private Element[] elementsField;
        
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public Element[] Elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Element {
        
        private Attribute[] attributesField;
        
        private Element[] elementsField;
        
        private ElementAction actionField;
        
        private string xPathField;
        
        private string nameField;
        
        private string valueField;
        
        private int orderField;
        
        private bool forceField;
        
        private bool forceFieldSpecified;
        
        private bool editField;
        
        private bool editFieldSpecified;
        
        private string targetXPathField;
        
        private string schemaField;
        
        private string complexTypeField;
        
        private string regexField;
        
        private string replaceField;
        
        private string printField;
        
        private ProcessingOrder processingOrderField;
        
        private bool useCDataField;
        
        private bool useCDataFieldSpecified;
        
        public Element() {
            this.orderField = 0;
            this.processingOrderField = ProcessingOrder.Document;
        }
        
        /// <remarks/>
        public Attribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public Element[] Elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public ElementAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ForceSpecified {
            get {
                return this.forceFieldSpecified;
            }
            set {
                this.forceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool Edit {
            get {
                return this.editField;
            }
            set {
                this.editField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool EditSpecified {
            get {
                return this.editFieldSpecified;
            }
            set {
                this.editFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string TargetXPath {
            get {
                return this.targetXPathField;
            }
            set {
                this.targetXPathField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string ComplexType {
            get {
                return this.complexTypeField;
            }
            set {
                this.complexTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Regex {
            get {
                return this.regexField;
            }
            set {
                this.regexField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Print {
            get {
                return this.printField;
            }
            set {
                this.printField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ProcessingOrder.Document)]
        public ProcessingOrder ProcessingOrder {
            get {
                return this.processingOrderField;
            }
            set {
                this.processingOrderField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool UseCData {
            get {
                return this.useCDataField;
            }
            set {
                this.useCDataField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool UseCDataSpecified {
            get {
                return this.useCDataFieldSpecified;
            }
            set {
                this.useCDataFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Attribute {
        
        private AttributeAction actionField;
        
        private string nameField;
        
        private string valueField;
        
        private bool forceField;
        
        private bool editField;
        
        public Attribute() {
            this.forceField = false;
            this.editField = false;
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public AttributeAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Edit {
            get {
                return this.editField;
            }
            set {
                this.editField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum AttributeAction {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Remove,
        
        /// <remarks/>
        Update,
        
        /// <remarks/>
        Rename,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum ElementAction {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Remove,
        
        /// <remarks/>
        Update,
        
        /// <remarks/>
        Rename,
        
        /// <remarks/>
        Move,
        
        /// <remarks/>
        DocumentUpdate,
        
        /// <remarks/>
        MoveAfter,
        
        /// <remarks/>
        ValidateSchema,
        
        /// <remarks/>
        RegexReplace,
        
        /// <remarks/>
        OrderBySchema,
        
        /// <remarks/>
        ParseSqlInsert,
        
        /// <remarks/>
        Print,
        
        /// <remarks/>
        Copy,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    public enum ProcessingOrder {
        
        /// <remarks/>
        Document,
        
        /// <remarks/>
        TopDown,
        
        /// <remarks/>
        BottomUp,
    }
}
